### ISSUE TITLE
Current version is limited to 102.0, will stop working when 102.0.1 is released

### ISSUE THREAD

**Issue by jobisoft** [bazuchan/thunderbird-deselect-on-delete#1]
Hi,

your extension passed a quick functionality test and seems to be compatible with Thunderbird 102, the next major version, which is to be released in June (in about two weeks). 

However, the max version setting of 102.0 is limiting this add-on to Thunderbird 102 Beta and your users will not be able to use it, when Thunderbird 102 ESR has been released.

If you also find, that your add-on is working as expected in Thunderbird 102, please submit a new version with a max setting of 102.* (changing the value on ATN only will prevent offline installs, which do not check the updated max version setting on ATN)

If you find errors which we missed, feel free to reach out for help: 
https://developer.thunderbird.net/add-ons/community

**Comment by bazuchan** [comment]
Submitted version 3.3 with new manifest

**Comment by jobisoft** [comment]
\o/ Thanks!

If you have time, could you remove the added console.log() statements, or uncomment them? Or do you expect issues and want those logs for debugging purposes when having to interact with users? Could you switch to console.debug() in that case?

**Comment by bazuchan** [comment]
Ooops, published wrong file. New version 3.4 is submitted.
