### ISSUE TITLE
Next Messages are still selected when deleting more than 1 Message

### ISSUE THREAD

**Issue by jdl96** [bazuchan/thunderbird-deselect-on-delete#2]
As the title says, if you delete more than 1 messsage, the next message will still be selected.
It seems that this addon only works when dealing with 1 message at a time.

I hope that this can be easily fixed because Thunderbird's auto-selection of the next message is extremely annoying and this addon does a great job of fixing the issue.

**Comment by bazuchan** [comment]
It is not easy to fix, because thunderbird has changed way it handles multiple deletions. I have spent couple of days trying to workaround it, but without any luck.

**Comment by jdl96** [comment]
Ah, that's unfortunate..
I do appreciate your efforts though! Hopefully in the future a solution will present itself.

**Comment by bazuchan** [comment]
Fixed by #4
